name = "cloudflare-serve"
main = "index.js"
compatibility_date = "2024-12-31"

# Uncomment and configure these when you're ready to deploy
# account_id = ""
# workers_dev = true
# route = ""
# zone_id = ""

